const OUT_FILED_CN = [
  '考核年月',
  '用户ID',
  '用户姓名',
  '用户编码',
  '产品线',
  '职级',
  '岗位ID',
  '岗位名称',
  '岗位编码',
  '岗位类型',
  '上级岗位ID',
  '上级岗位编码',
  '在岗人数',
  '岗位数',
  '汇总目标联系人',
  '目标联系人标准',
  '目标联系人达成率',
  '非目标联系人数',
  '目标医生数',
  '目标医生标准',
  '目标医生达成率',
  '非目标医生数',
  '目标商业联系人数',
  '目标商业联系人标准',
  '目标商业联系人达成率',
  '非目标商业联系人数',
  '目标政府/学会联系人数',
  '目标政府/学会联系人标准',
  '目标政府/学会联系人达成率',
  '非目标政府/学会联系人数',
  '区域内工作天数',
  '区域内工作天数标准',
  '区域内工作天数达成',
  'A级拜访',
  'A级联系人',
  'A级联系人拜访频率',
  'A级联系人拜访频率标准',
  'A级联系人拜访频率达成',
  'B级拜访',
  'B级联系人',
  'B级联系人拜访频率',
  'B级联系人拜访频率标准',
  'B级联系人拜访频率达成',
  'V级拜访',
  'V级联系人',
  'V级联系人拜访频率',
  'V级联系人拜访频率标准',
  'V级联系人拜访频率达成',
  '总拜访量',
  '目标联系人拜访次数',
  '非目标联系人拜访次数',
  '院会',
  '院会标准',
  '院会达成',
  '销售拜访辅导',
  '销售拜访辅导标准',
  '销售拜访辅导达成',
  '会议辅导',
  '会议辅导标准',
  '会议辅导达成',
  '区域辅导',
  '区域辅导标准',
  '区域辅导达成', // 这是DSM和RSM有的
  '实地协访',
  '实地协访标准',
  '实地协访达成', // 这是RSM专有
];
const OUT_FILED_EN = [
  'YM',
  'UserID',
  'UserName',
  'UserCode',
  'ProductName',
  'Level',
  'TerritoryID',
  'TerritoryName',
  'TerritoryCode',
  'TerritoryType',
  'ParentTerritoryID',
  'ParentTerritoryCode',
  'OnPositionNumber',
  'PositionNumber',
  'CustomerNumber',
  'TargetCustomerNumber',
  'TargetCustomerRate',
  'NonTargetCustomerNumber',
  'DoctorNumber',
  'DoctorTargetNumber',
  'DoctorAchiRate',
  'DoctorNonTargetNumber',
  'DisNumber',
  'DisTargetNumber',
  'DisAchiRate',
  'DisNonTargetNumber',
  'GovSocNumber',
  'GovSocTargetNumber',
  'GovSocAchiRate',
  'GovSocNonTargetNumber',
  'WorkingDays',
  'WorkingDaysTarget',
  'WorkingDaysAchiRate',
  'ACustomerCallNumber',
  'ACustomer',
  'ACustomerCallRate',
  'ACustomerCallTarget',
  'ACustomerCallAchiRate',
  'BCustomerCallNumber',
  'BCustomer',
  'BCustomerCallRate',
  'BDoctorCallTarget',
  'BDoctorCallAchiRate',
  'VCustomerCallNumber',
  'VCustomer',
  'VCustomerCallRate',
  'VCustomerCallTarget',
  'VCustomerCallAchiRate',
  'TotalCallNumber',
  'TargetCallNumber',
  'NonTargetCallNumber',
  'HospitalEventNumber',
  'HospitalTarget',
  'HospitalAchiRate',
  'SalesCoach',
  'SalesCoachTarget',
  'SalesCoachAchiRate',
  'MeetingCoach',
  'MeetingCoachTarget',
  'MeetingCoachAchiRate',
  'AssistCoach',
  'AssistCoachTarget',
  'AssistCoachAchiRate', // 这是DSM和RSM有的
  'RegionalCoach',
  'RegionalCoachTarget',
  'RegionalCoachAchiRate', // 这是RSM专有
];

const OUT_FILED = {
  考核年月: 'YM',
  用户ID: 'UserID',
  用户姓名: 'UserName',
  用户编码: 'UserCode',
  产品线: 'ProductName',
  职级: 'Level',
  岗位ID: 'TerritoryID',
  岗位名称: 'TerritoryName',
  岗位编码: 'TerritoryCode',
  岗位类型: 'TerritoryType',
  上级岗位ID: 'ParentTerritoryID',
  上级岗位编码: 'ParentTerritoryCode',
  在岗人数: 'OnPositionNumber',
  岗位数: 'PositionNumber',
  汇总目标联系人: 'CustomerNumber',
  目标联系人标准: 'TargetCustomerNumber',
  目标联系人达成率: 'TargetCustomerRate',
  非目标联系人数: 'NonTargetCustomerNumber',
  目标医生数: 'DoctorNumber',
  目标医生标准: 'DoctorTargetNumber',
  目标医生达成率: 'DoctorAchiRate',
  非目标医生数: 'DoctorNonTargetNumber',
  目标商业联系人数: 'DisNumber',
  目标商业联系人标准: 'DisTargetNumber',
  目标商业联系人达成率: 'DisAchiRate',
  非目标商业联系人数: 'DisNonTargetNumber',
  '目标政府/学会联系人数': 'GovSocNumber',
  '目标政府/学会联系人标准': 'GovSocTargetNumber',
  '目标政府/学会联系人达成率': 'GovSocAchiRate',
  '非目标政府/学会联系人数': 'GovSocNonTargetNumber',
  区域内工作天数: 'WorkingDays',
  区域内工作天数标准: 'WorkingDaysTarget',
  区域内工作天数达成: 'WorkingDaysAchiRate',
  A级拜访: 'ACustomerCallNumber',
  A级联系人: 'ACustomer',
  A级联系人拜访频率: 'ACustomerCallRate',
  A级联系人拜访频率标准: 'ACustomerCallTarget',
  A级联系人拜访频率达成: 'ACustomerCallAchiRate',
  B级拜访: 'BCustomerCallNumber',
  B级联系人: 'BCustomer',
  B级联系人拜访频率: 'BCustomerCallRate',
  B级联系人拜访频率标准: 'BDoctorCallTarget', // BCustomerCallTarget
  B级联系人拜访频率达成: 'BDoctorCallAchiRate', // BCustomerCallAchiRate
  V级拜访: 'VCustomerCallNumber',
  V级联系人: 'VCustomer',
  V级联系人拜访频率: 'VCustomerCallRate',
  V级联系人拜访频率标准: 'VCustomerCallTarget',
  V级联系人拜访频率达成: 'VCustomerCallAchiRate',
  总拜访量: 'TotalCallNumber',
  目标联系人拜访次数: 'TargetCallNumber',
  非目标联系人拜访次数: 'NonTargetCallNumber',
  院会: 'HospitalEventNumber',
  院会标准: 'HospitalTarget',
  院会达成: 'HospitalAchiRate',
  销售拜访辅导: 'SalesCoach',
  销售拜访辅导标准: 'SalesCoachTarget',
  销售拜访辅导达成: 'SalesCoachAchiRate',
  会议辅导: 'MeetingCoach',
  会议辅导标准: 'MeetingCoachTarget',
  会议辅导达成: 'MeetingCoachAchiRate',
  区域辅导: 'AssistCoach',
  区域辅导标准: 'AssistCoachTarget',
  区域辅导达成: 'AssistCoachAchiRate', // 这是DSM和RSM有的
  实地协访: 'RegionalCoach',
  实地协访标准: 'RegionalCoachTarget',
  实地协访达成: 'RegionalCoachAchiRate', // 这是RSM专有
};
